### ISSUE TITLE
Doesn't support the new RPGM MV format

### ISSUE THREAD

**Issue by cooperdk** [emerladCoder/RPG-Maker-MV-Cheat-Menu-Plugin#5] opened 2021-12-25 02:47 UTC
Hi,
you need to adapt your cheat injector to match the new RPG Maker MV format (the one without a www folder, and with a game executable which is essentially a nw.js runtime. In this version, the data files are all in the root folder and therefore, the plugins.js is not under \www\js but just under \js.

I installed it the manual way, unfortunately, that didn't work.

**Comment by NamelessMagician** [comment] 2023-05-21 17:55
I have created a PR #9 with support for the newer MZ build format. Downloads are available from my fork.

**Comment by emerladCoder** [comment] 2023-06-12 06:58
Duplicate of issue #4 , closed with PR #9

**Closed by emerladCoder** 2023-06-12 06:58 UTC
